##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
stem_identifier:                  'tutorial_restricted_scan_analysis'
numjobs:                          1
Nevents_per_job:                  100
Nevents:                          100
common_norm_matrices:             True

dark_matter_spectral_model:       Z2_ScalarSinglet

seed:                             0
save_path:                        "data/tutorial_restricted_scan_analysis/"
num_in_marg_batch:                10
num_in_mixture_scanning_batch:    10

# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters

signal_fraction:                  0.01
ccr_of_bkg_fraction:              0.8
diffuse_of_astro_fraction:        0.3
dmdensity_profile:                'einasto'
dark_matter_mass:                 1.0

# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.
true_energy_bins_per_decade:      100
true_spatial_res:                 0.2
true_longitude_min:               -2.31
true_longitude_max:               2.31
true_latitude_min:                -2.
true_latitude_max:                2.0

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.
recon_energy_bins_per_decade:     50
recon_spatial_res:                0.2
recon_longitude_min:              -2.31
recon_longitude_max:              2.31
recon_latitude_min:               -2.
recon_latitude_max:               2.0


##################################################################
### Inference/Analysis Parameters



# Dark Matter Inference Parameters
parameter_specifications:
  'Z2 dark matter':
  
    spectral_parameters:
      'mass':
        discrete: True
        scaling: 'log10'
        bounds: 'event_dynamic'
        absolute_bounds: [1e-1, 1e2]
        num_events: 1e4
        dynamic_multiplier: 2
        default_value: 1.0
        bins: 31
      # 'lahS':
      #   discrete: True
      #   scaling: 'log10'
      #   bounds: 'event_dynamic'
      #   absolute_bounds: [1e-2, 1e0]
      #   num_events: 1e2
      #   dynamic_multiplier: 7
      #   default_value: 0.1
      #   bins: 21

    # spatial_parameters:
    #   'alpha':
    #     discrete: True
    #     scaling: 'log10'
    #     bounds: 'event_dynamic'
    #     num_events: 1e2
    #     dynamic_multiplier: 3
    #     absolute_bounds: [1e-2, 1e1]
    #     bins: 31
    #     default_value: 0.17


mixture_fraction_specifications:
  'sig|total':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]
  'ccr|bkg':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]
  'diffuse|astro':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]

