##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
immediate_run:                    False
env_name:                         GammaBayesEnv
jobname:                          'local_misc_testing'
stem_identifier:                  'local_misc_testing'
numjobs:                          1
Nevents_per_job:                  2
Nevents:                          2
common_norm_matrices:             False
mem_for_matrix_gen:               400 #in MB
time_for_matrix_gen_hrs:          1
time_for_matrix_gen_mins:         0

# If using common log irf normalisations one must provide the 
  # path to the numpy files containing them individually
# log_psf_norm_matrix_path:       'path'
# log_edisp_norm_matrix_path:     'path'

# Time and memory here is completely random. 
# Run small test job to figure out time and memory allocation
mem_per_cpu:                      12000
numcores:                         8
time_hrs:                         1
time_mins:                        0
mail_progress:                    True
mail_address:                     progressemail1999@gmail.com
dark_matter_spectral_model:       Z2_ScalarSinglet

hyper_parameter_scan_class:       dynesty_stochastic_reweighting_class
seed:                             0
save_path:                        "data/local_misc_testing/"
num_in_marg_batch:                10
num_in_mixture_scanning_batch:    10

# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters

signal_fraction:                  0.5
ccr_of_bkg_fraction:              1.0
diffuse_of_astro_fraction:        0.5
dmdensity_profile:                'einasto'
dark_matter_mass:                 1.0

# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.

true_energy_bins_per_decade:      100
true_spatial_res:                 0.2

true_longitude_min:               -3.
true_longitude_max:               3.
true_latitude_min:                -3.
true_latitude_max:                3.

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.
recon_energy_bins_per_decade:     50
recon_spatial_res:                0.4
recon_longitude_min:              -3.
recon_longitude_max:              3.
recon_latitude_min:               -3.
recon_latitude_max:               3.


##################################################################
### Inference/Analysis Parameters



# Dark Matter Inference Parameters
parameter_specifications:
  'Z2 dark matter':
  
    spectral_parameters:
      'mass':
        discrete: True
        scaling: 'log10'
        bounds: [1e-1,1e2]
        default_value: 1.0
        bins: 7

    spatial_parameters:

      'alpha':
        discrete: True
        scaling: 'log10'
        bounds: [1.7e-2,1.7] # Making sure the value set in the sim is used
        bins: 7
        default_value: 0.17


mixture_fraction_specifications:
  'sig|total':
    discrete: True
    scaling: 'linear'
    bins: 41
    bounds: [0., 1.0]
  'ccr|bkg':
    discrete: True
    scaling: 'linear'
    bins: 41
    bounds: [0., 1.0]
  'diffuse|astro':
    discrete: True
    scaling: 'linear'
    bins: 41
    bounds: [0., 1.0]



# Debugging and plotting arguments
diagnostics:      False
blockplot:        True