##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
stem_identifier:                  'multicomp_param_test'
numjobs:                          1
Nevents_per_job:                  1000
Nevents:                          1000
common_norm_matrices:             True

seed:                             0
save_path:                        "data/tutorial_restricted_scan_analysis/"
num_in_marg_batch:                10
num_in_mixture_scanning_batch:    10

# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters

gauss1_fraction:                  0.25
gauss2_fraction:                  0.33333333333333333333333333333333333
gauss3_fraction:                  0.5

# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.
true_energy_bins_per_decade:      100
true_spatial_res:                 0.1
true_longitude_min:               -3.
true_longitude_max:               3.
true_latitude_min:                -3.
true_latitude_max:                3.

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.
recon_energy_bins_per_decade:     50
recon_spatial_res:                0.1
recon_longitude_min:              -3.
recon_longitude_max:              3.
recon_latitude_min:               -3.
recon_latitude_max:               3.


##################################################################
### Inference/Analysis Parameters



# Dark Matter Inference Parameters
prior_parameter_specifications:
  'Gauss1':
  
    spectral_parameters:
      'loc':
        discrete: True
        scaling: 'log10'
        bounds: [7e-1, 1.5e0]
        default_value: 1.0
        bins: 21

    spatial_parameters:
      'scale':
        discrete: True
        scaling: 'log10'
        bounds: [8e-2, 1.2e-1]
        default_value: 0.1
        bins: 34

  'Gauss2':
    spectral_parameters:
      'loc':
        discrete: True
        scaling: 'log10'
        bounds: [9.5e0, 1.05e1]
        default_value: 10.0
        bins: 43

    spatial_parameters:
      'scale':
        discrete: True
        scaling: 'log10'
        bounds: [1e0,5e0]
        default_value: 3.0
        bins: 31


mixture_fraction_specifications:
  'Gauss1|total':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]

  'Gauss2|Gauss345':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]

  'Gauss3|Gauss4':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]

