##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
stem_identifier:                  'standard_analysis_default'
jobname:                          '1'
numjobs:                          1
Nevents_per_job:                  100
Nevents:                          100
common_norm_matrices:             True

dark_matter_spectral_model:       Z2_ScalarSinglet
dark_matter_density_profile:      Einasto_Profile

hyper_parameter_scan_class:         DiscreteAdaptiveScan
mixture_fraction_exploration_type:  'sample'
marginalisation_bounds:             [['log10', 0.36], ['linear', 0.44], ['linear', 0.44]]


seed:                             24
save_path:                        "data/standard_analysis_default/"
num_in_marg_batch:                10
num_in_mixture_scanning_batch:    10


# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters

signal_fraction:                  0.1
ccr_of_bkg_fraction:              0.8
diffuse_of_astro_fraction:        0.3
dark_matter_mass:                 1.0

# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.
true_energy_bins_per_decade:      100
true_spatial_res:                 0.2
true_longitude_min:               -3.
true_longitude_max:               3.
true_latitude_min:                -3.
true_latitude_max:                3.

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.
recon_energy_bins_per_decade:     50
recon_spatial_res:                0.2
recon_longitude_min:              -3.
recon_longitude_max:              3.
recon_latitude_min:               -3.
recon_latitude_max:               3.


##################################################################
### Inference/Analysis Parameters



# Dark Matter Inference Parameters
prior_parameter_specifications:
  'Z2 dark matter':
  
    spectral_parameters:
      'mass':
        discrete: True
        scaling: 'log10'
        bounds: 'event_dynamic'
        absolute_bounds: [1e-1, 1e2]
        num_events: 1e2
        dynamic_multiplier: 3
        default_value: 1.0
        bins: 31
      # 'lahS':
      #   discrete: True
      #   scaling: 'log10'
      #   bounds: 'event_dynamic'
      #   absolute_bounds: [1e-2, 1e0]
      #   num_events: 1e2
      #   dynamic_multiplier: 7
      #   default_value: 0.1
      #   bins: 21

    spatial_parameters:
      'alpha':
        discrete: True
        scaling: 'log10'
        bounds: 'event_dynamic'
        num_events: 1e2
        dynamic_multiplier: 3
        absolute_bounds: [1e-2, 1e1]
        bins: 31
        default_value: 0.17


mixture_fraction_specifications:
  'sig|total':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]
  'ccr|bkg':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]
  'diffuse|astro':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.0]

