
identifier        : 'example_config_file_run'
Nevents           : 1000
logmass           : -0.1
xi                : 0.8
nbins_logmass     : 81
nbins_xi          : 161
dmdensity_profile : "einasto"
numcores          : 8
runnumber         : 1
totalevents       : 1000
