##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
immediate_run:                    False
env_name:                         GammaBayesEnv
jobname:                          'local_BF_Testing'
stem_identifier:                  'local_BF_Testing'
numjobs:                          1
Nevents_per_job:                  2000
Nevents:                          2000
common_norm_matrices:             False
mem_for_matrix_gen:               400 #in MB
time_for_matrix_gen_hrs:          1
time_for_matrix_gen_mins:         0

# If using common log irf normalisations one must provide the 
  # path to the numpy files containing them individually
# log_psf_norm_matrix_path:       'path'
# log_edisp_norm_matrix_path:     'path'

# Time and memory here is completely random. 
# Run small test job to figure out time and memory allocation
mem_per_cpu:                      12000
numcores:                         8
time_hrs:                         1
time_mins:                        0
mail_progress:                    True
mail_address:                     progressemail1999@gmail.com
dark_matter_spectral_model:       Z2_ScalarSinglet

hyper_parameter_scan_class:       dynesty_stochastic_reweighting_class
seed:                             0
save_path:                        "data/local_BF_Testing/"
num_in_marg_batch:                10
num_in_mixture_scanning_batch:    10

# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters

# Currently the only nicely supported mixture models are via
  # sitck breaking dirichlet processes. 
  # "ZZ_fraction" refers to the fraction of ZZ output to everything else
  # "WW_fraction" refers to the fraction of W+W- output to what's leftover
    # after subtracting the ZZ events
  # "HH_fraction" refers to the fraction of HH output to what's leftover
    # after subtracting the ZZ AND WW events
  # etc
DM_Annihilation_Stick_Breaking_Ratios:

  ZZ_fraction:                      0.222222222222222222     # 0.05/(1-0.05)
  WW_fraction:                      0.666666666666666666
  HH_fraction:                      0.1       # 0.05/(1-0.05)/(1-0.052)
  tt_fraction:                      0.1
  gg_fraction:                      0.1

signal_fraction:                  0.2
ccr_of_bkg_fraction:              0.8
diffuse_of_astro_fraction:        0.4
dmdensity_profile:                'einasto'
mass:                             0.75



# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.

true_energy_bins_per_decade:      200
true_spatial_res:                 0.2

true_longitude_min:               -3.1
true_longitude_max:               3.1
true_latitude_min:                -3.
true_latitude_max:                3.

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.

recon_energy_bins_per_decade:     50
recon_spatial_res:                0.4

recon_longitude_min:              -3.1
recon_longitude_max:              3.1
recon_latitude_min:               -3.
recon_latitude_max:               3.


##################################################################
### Inference/Analysis Parameters

shared_parameter_specifications:
  'single channel specifications':
    spectral_parameters:
      mass:
        discrete: True
        scaling: 'log10'
        bounds: 'event_dynamic'
        absolute_bounds: [1e-1, 1e2]
        dynamic_multiplier: 1
        num_events: 1e4
        default_value: 0.75
        bins: 61



# Dark Matter Inference Parameters
parameter_specifications: {}


mixture_fraction_exploration_type: 'sample'

mixture_fraction_specifications:

  'ZZ frac':
    discrete: False
    scaling: 'log10'
    bounds: [0., 1.]
  'W+W- frac':
    discrete: False
    scaling: 'log10'
    bounds: [0., 1.]  
  'HH frac':
    discrete: False
    scaling: 'log10'
    bounds: [0., 1.] 
  'tt frac':
    discrete: False
    scaling: 'log10'
    bounds: [0., 1.] 
  'gg frac':
    discrete: False
    scaling: 'log10'
    bounds: [0., 1.] 
  'ccr|bkg':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.]
  'diffuse|astro':
    discrete: False
    scaling: 'linear'
    bounds: [0., 1.]





# Debugging and plotting arguments
diagnostics:      False
blockplot:        True