signalfraction:                   0.5
Nevents:                          100
nbins_mass:                       31
nbins_signalfraction:             161
dmdensity_profile:                'nfw'
mass:                             1.0
mass_upper_bd_for_inference:      2.
mass_lower_bd_for_inference:      -1.
numcores:                         6
sigfrac_upper_bd:                 1.
sigfrac_lower_bd:                 0.
sigfrac_upper_bd_for_inference:   1.
sigfrac_lower_bd_for_inference:   0.
sigfrac_spacing:                  'linear'


true_energy_min:                  0.1
true_energy_max:                  100
true_energy_bins_per_decade:      50
true_spatial_res:                 0.2
true_longitude_min:               -2.5
true_longitude_max:               2.5
true_latitude_min:                -2
true_latitude_max:                2

recon_energy_min:                 0.1
recon_energy_max:                 100
recon_energy_bins_per_decade:     50
recon_spatial_res:                0.4
recon_longitude_min:              -2.5
recon_longitude_max:              2.5
recon_latitude_min:               -2
recon_latitude_max:               2