##################################################################
##################################################################
### OZSTAR RESOURCE ALLOCATIONS
##################################################################
##################################################################

# # Run the simulation, nuisance parameter marginalisation and posterior generation in one job?
immediate_run:                    False
env_name:                         GammaBayesEnv
jobname:                          'local_BF_Testing'
stem_identifier:                  'local_BF_Testing'
numjobs:                          1
Nevents_per_job:                  10000
NumEvents:                        10000
common_norm_matrices:             True
log_irf_norm_matrix_load_path:    'irf_norm_matrix.npy'

mem_for_matrix_gen:               400 #in MB
time_for_matrix_gen_hrs:          1
time_for_matrix_gen_mins:         0

# If using common log irf normalisations one must provide the 
  # path to the numpy files containing them individually
# log_psf_norm_matrix_path:       'path'
# log_edisp_norm_matrix_path:     'path'

# Time and memory here is completely random. 
# Run small test job to figure out time and memory allocation
mem_per_cpu:                      12000
numcores:                         8
time_hrs:                         1
time_mins:                        0
mail_progress:                    True
mail_address:                     progressemail1999@gmail.com
# dark_matter_spectral_model:       Z2_ScalarSinglet

hyper_parameter_scan_class:       DiscreteAdaptiveScan
seed:                             0
save_path:                        "data/local_BF_Testing/"
num_marginalisation_batches:      8
num_in_mixture_scanning_batch:    1
num_simulation_batches:           8
# marginalisation_bounds:           [0.4, 0.5, 0.5]

# The larger this bugger the more values are considered at once when vectorised
  # This also leads to a subsequent increase in memory. Currently this must be
  # chosen with a bit of trial and error
mixture_scanning_buffer:          1

##################################################################
##################################################################
### GAMMABAYES RUN PARAMETERS
##################################################################
##################################################################


##################################################################
### Simulation Parameters


DM_Annihilation_Ratios:

  'ZZ':                       0.30777537433767554
  'W+W-':                     0.606028581284285
  'HH':                       0.06222169472353944
  'tt':                       0.023954021966799327
  'gg':                       1.0065389782412841e-05
  'bb':                       5.37454478928206e-06
  # 'tau+tau-':                 9.61116976e-07
  # 'cc':                       3.57489300e-07
  # 'gammagamma':               4.07302152e-74
  # 'nuenue':                   0.
  # 'e+e-':                     0.
  # 'numunumu':                 0.
  # 'mu+mu-':                   0.
  # 'nutaunutau':               0.
  # 'ss':                       0.
  # 'dd':                       0.
  # 'uu':                       0.


DM_Channels:                      ['ZZ', 'WW', 'HH','tt',
                                    'gg','bb'] #,'tau+tau-',
                                    # 'cc','gammagamma', 'nuenue',
                                    # 'e+e-','numunumu','mu+mu-',
                                    # 'nutaunutau','ss','dd','uu']


true_mixture_fractions: 
  DM:                     0.8

  'Fermi-Gaggero Diffuse':    0.04
  'HESS Catalogue Sources Prior': 0.06

  CCR_BKG:                    0.1

dark_matter_density_profile:      'Einasto_Profile'
dark_matter_mass:                 10.



# Parameters for the 'true' value axes for gamma ray events
true_energy_min:                  0.2
true_energy_max:                  90.

true_energy_bins_per_decade:      100
true_spatial_res:                 0.2

true_longitude_min:               -3.1
true_longitude_max:               3.1
true_latitude_min:                -3.
true_latitude_max:                3.

# Parameters for the reconstructed value axes for gamma ray events
recon_energy_min:                 0.2
recon_energy_max:                 90.

recon_energy_bins_per_decade:     10
recon_spatial_res:                0.4

recon_longitude_min:              -3.1
recon_longitude_max:              3.1
recon_latitude_min:               -3.
recon_latitude_max:               3.


IRF_kwarg_Specifications:
  prod_vers: '5'


##################################################################
### Inference/Analysis Parameters

shared_parameter_specifications:
  'single channel specifications':
    spectral_parameters:
      mass:
        discrete: True
        scaling: 'log10'
        bounds: 'event_dynamic'
        absolute_bounds: [1e-1, 1e2]
        dynamic_multiplier: 5
        num_events: 1e4
        default_value: 10.
        bins: 121
        shared_models: 
          ['ZZ DM Class', 'W+W- DM Class', 'HH DM Class',
          'tt DM Class',  'gg DM Class', 'bb DM Class']



# Dark Matter Inference Parameters
prior_parameter_specifications: {}

mixture_layout: 
  [
    {'DM': 
    ['ZZ DM Class', 'W+W- DM Class', 'HH DM Class',
      'tt DM Class',  'gg DM Class', 'bb DM Class']},
    'Fermi-Gaggero Diffuse', 'HESS Catalogue Sources Prior', 'CCR_BKG',
  ]


mixture_parameter_specifications:

  'ZZ DM Class':
    discrete: False
    bounds: [0., 1.]
    dependent: ['W+W- DM Class', 'HH DM Class', 'tt DM Class', 'gg DM Class', 'bb DM Class']
    custom_dist_name: 'dirichlet'
    custom_dist_kwargs: 
      alpha: [1., 1., 1., 1., 1., 1., ]
  'W+W- DM Class':
    discrete: False
    bounds: [0., 1.]
  'HH DM Class':
    discrete: False
    bounds: [0., 1.]
  'tt DM Class':
    discrete: False
    bounds: [0., 1.]
  'gg DM Class':
    discrete: False
    bounds: [0., 1.]
  'bb DM Class':
    discrete: False
    bounds: [0., 1.]


  
  'DM':
    discrete: False
    bounds: [0., 1.]
    dependent: ['Fermi-Gaggero Diffuse', 'HESS Catalogue Sources Prior','CCR_BKG']
    custom_dist_name: 'dirichlet'
    custom_dist_kwargs: 
      alpha: [1., 1., 1., 1.]
  'Fermi-Gaggero Diffuse':
    discrete: False
    bounds: [0., 1.]
  'HESS Catalogue Sources Prior':
    discrete: False
    bounds: [0., 1.]
  'CCR_BKG':
    discrete: False
    bounds: [0., 1.]




# Debugging and plotting arguments
diagnostics:      False
blockplot:        True