
identifier        : 'example_config_run'
Nevents           : 1000
logmass           : 1.0
xi                : 0.5
nbins_logmass     : 101
nbins_xi          : 161
dmdensity_profile : "einasto"
numcores          : 8
runnumber         : 3
totalevents       : 1000
batch_job         : 0


log10_true_energy_min   : -0.5
log10_true_energy_max   : 1.5
log10_true_energy_bins_per_decade : 300
true_spatial_res        : 0.2
true_longitude_min      : -3.5
true_longitude_max      : 3.5
true_latitude_min       : -3.1
true_latitude_max       : 3.1


log10_recon_energy_min   : -0.5
log10_recon_energy_max   : 1.5
log10_recon_energy_bins_per_decade : 50
recon_spatial_res        : 0.4
recon_longitude_min      : -3.5
recon_longitude_max      : 3.5
recon_latitude_min       : -3.1
recon_latitude_max       : 3.1
