name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build

      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.DEFINITELY_NOT_TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository testpypi dist/*
        id: testpypi_upload

      - name: Publish to PyPI
        if: ${{ steps.testpypi_upload.conclusion == 'success' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.DEFINITELY_NOT_PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
